# Cấu hình cho Q‑learning
q_learning:
  alpha: 0.1          # learning rate
  gamma: 0.99         # discount factor
  epsilon: 1.0        # khởi đầu exploration
  eps_min: 0.1       # epsilon tối thiểu
  eps_decay: 0.99999585    # hệ số giảm epsilon mỗi step
 
# Cấu hình cho DQN
dqn:
  input_dim: 132              # 2 node info + 26 cạnh * 5 đặc trưng
  hidden_dims: [128, 128]
  lr: 0.001
  gamma: 0.99
  epsilon: 1.0
  eps_min: 0.01
  eps_decay: 0.9995
  batch_size: 64
  buffer_capacity: 10000
  target_update_freq: 100

# Cấu hình huấn luyện chung
training:
  num_episodes: 3000
  print_every: 200
  save_every: 500
  checkpoint_dir: checkpoints
  log_dir: logs